# Generated by Django 6.0.1 on 2026-01-15 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itcourse',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='software',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
